name: Configure Reverse Proxy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy and Configure Reverse Proxy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Copy the reverse-proxy.conf file to the EC2 instance
            scp -i ${{ secrets.KEY }} -P ${{ secrets.PORT }} httpd-reverse-proxy/reverse-proxy.conf ${{ secrets.USER }}@${{ secrets.HOST }}:/tmp/reverse-proxy.conf

            # Verify if the file is copied to the remote server
            ssh -i ${{ secrets.KEY }} -p ${{ secrets.PORT }} ${{ secrets.USER }}@${{ secrets.HOST }} 'ls -l /tmp/reverse-proxy.conf'

            # Move the configuration file to the Apache configuration directory
            ssh -i ${{ secrets.KEY }} -p ${{ secrets.PORT }} ${{ secrets.USER }}@${{ secrets.HOST }} 'sudo mv /tmp/reverse-proxy.conf /etc/httpd/conf.d/reverse-proxy.conf'

            # Restart Apache HTTPD to apply the new configuration
            ssh -i ${{ secrets.KEY }} -p ${{ secrets.PORT }} ${{ secrets.USER }}@${{ secrets.HOST }} 'sudo systemctl restart httpd'
