name: Deploy Apache Configuration

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/private_key
          chmod 600 /tmp/private_key

          # Create known_hosts file
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} "echo SSH connection successful"

      - name: Deploy to Server
        run: |
          scp -i /tmp/private_key -o StrictHostKeyChecking=no reverse-proxy.conf ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/etc/httpd/conf.d/
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} "sudo systemctl restart httpd"
