name: Configure Reverse Proxy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Reverse Proxy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Check if the reverse-proxy.conf file exists
            if [ ! -f /tmp/reverse-proxy.conf ]; then
              echo "File /tmp/reverse-proxy.conf not found. Exiting."
              exit 1
            fi
            
            # Move the configuration file to the Apache configuration directory
            sudo mv /tmp/reverse-proxy.conf /etc/httpd/conf.d/reverse-proxy.conf
            
            # Restart Apache HTTPD to apply the new configuration
            sudo systemctl restart httpd
